spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
---

spring:
  profiles: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8081

response.msg: The file has been sent.

kafka.broker: localhost:29092
enable.auto.commit: true
auto.commit.interval.ms:  100
group.id: group1
kafka.auto.offset.reset: earliest
kafka.topic: voice

---

spring:
  profiles: stage
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

response.msg: The file has been sent.

---

spring:
  profiles: prod
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

response.msg: The file has been sent.


---